### PR TITLE
COPFE-37 add basic renovate file

### PR DESCRIPTION
**Pull request by leolimajr**
* add disclaimer on README.md file

Signed-off-by: Leo Lima <leo.lima@rio.cloud>

### CODE REVIEW

**Comment by rkipsch** [comment]
Hey Leo,
do you think it would make sense to pre-define the structure a bit more in detail as well as suggest the commit prefix for being aligned with other projects? This way it is easier to understand the props and to add new settings. Like:
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [],
  "commitMessagePrefix": "Renovate:",
  "schedule": [],
  "timezone": "Europe/Berlin",
  "prConcurrentLimit": 1,
  "ignorePaths": [],
  "ignoreDeps": [],
  "packageRules": []
}
```

**Comment by leolimajr** [comment]
@rkipsch most of teams use custom rules across projects by defining  a centralised control of configs, which can be achieved by using the extends clause. So they don't define it per project basis. Example:

```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "local>MYROJECT/config-renovate:spa"
  ]
}
```

But I think it is sensible to keep a minimal set of configs as you suggested. I'll update my commit soon.

**Comment by leolimajr** [comment]
@rkipsch done ;)

**Comment by rkipsch** [comment]
I understand. Funny enough, I know some projects where it is the other way around and defined per project. But that might also be due to different setups like create-react-app and newer vite setups with different dependencies.

But thanks for updating the PR again :-)

**Pull request merged**
